# Generated by Django 2.1.4 on 2019-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutes',
            old_name='minutestitle',
            new_name='minutesstitle',
        ),
        migrations.AddField(
            model_name='minutes',
            name='minutesdate',
            field=models.DateField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='minutes',
            name='minutestext',
            field=models.CharField(max_length=500),
        ),
    ]
