# Generated by Django 2.1.4 on 2019-02-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20190207_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutes',
            old_name='minutesstitle',
            new_name='minutestitle',
        ),
    ]
