# Generated by Django 2.1.4 on 2019-02-07 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0003_auto_20190207_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingagenda',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourcedescription',
            field=models.TextField(),
        ),
    ]
